packages:
  - apps/*
  - packages/*

# ビルドを許可する依存パッケージ
only-built-dependencies:
  - '@biomejs/biome'
  - '@types/node'
  - 'lint-staged'
  - 'sort-package-json'
  - 'typescript'
  - 'vitest'
  - 'honkit'

catalog:
  '@biomejs/biome': 2.3.10
  '@types/node': 25.0.3
  honkit: 6.1.4
  lint-staged: 16.2.7
  sort-package-json: 3.6.0
  typescript: 5.9.3
  vitest: 2.1.8

catalogMode: strict

cleanupUnusedCatalogs: true
