packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.10
  '@types/node': 25.0.3
  honkit: 6.1.4
  lint-staged: 16.2.7
  sort-package-json: 3.6.0
  typescript: 5.9.3
  vitest: 4.0.16

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - esbuild
